export default {
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    PROFILE: "PROFILE",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    SEND_RESET_PASSWORD_EMAIL: "SEND_RESET_PASSWORD_EMAIL",
    RESET_PASSWORD: " RESET_PASSWORD",
    TYPE: 'TYPE',
    CATEGORY: 'CATEGORY',
    PAYMENT: 'PAYMENT',
    TRANSACTION: 'TRANSACTION',
    TOTAL_TRANSACTION: 'TOTAL_TRANSACTION'

}